// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/image/image.proto

package go_micro_srv_image

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreateAlbumReq struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateAlbumReq) Reset()         { *m = CreateAlbumReq{} }
func (m *CreateAlbumReq) String() string { return proto.CompactTextString(m) }
func (*CreateAlbumReq) ProtoMessage()    {}
func (*CreateAlbumReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_a8e6376c21f4d969, []int{0}
}

func (m *CreateAlbumReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateAlbumReq.Unmarshal(m, b)
}
func (m *CreateAlbumReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateAlbumReq.Marshal(b, m, deterministic)
}
func (m *CreateAlbumReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateAlbumReq.Merge(m, src)
}
func (m *CreateAlbumReq) XXX_Size() int {
	return xxx_messageInfo_CreateAlbumReq.Size(m)
}
func (m *CreateAlbumReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateAlbumReq.DiscardUnknown(m)
}

var xxx_messageInfo_CreateAlbumReq proto.InternalMessageInfo

func (m *CreateAlbumReq) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type CreateAlbumResp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateAlbumResp) Reset()         { *m = CreateAlbumResp{} }
func (m *CreateAlbumResp) String() string { return proto.CompactTextString(m) }
func (*CreateAlbumResp) ProtoMessage()    {}
func (*CreateAlbumResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_a8e6376c21f4d969, []int{1}
}

func (m *CreateAlbumResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateAlbumResp.Unmarshal(m, b)
}
func (m *CreateAlbumResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateAlbumResp.Marshal(b, m, deterministic)
}
func (m *CreateAlbumResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateAlbumResp.Merge(m, src)
}
func (m *CreateAlbumResp) XXX_Size() int {
	return xxx_messageInfo_CreateAlbumResp.Size(m)
}
func (m *CreateAlbumResp) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateAlbumResp.DiscardUnknown(m)
}

var xxx_messageInfo_CreateAlbumResp proto.InternalMessageInfo

type DeleteAlbumReq struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteAlbumReq) Reset()         { *m = DeleteAlbumReq{} }
func (m *DeleteAlbumReq) String() string { return proto.CompactTextString(m) }
func (*DeleteAlbumReq) ProtoMessage()    {}
func (*DeleteAlbumReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_a8e6376c21f4d969, []int{2}
}

func (m *DeleteAlbumReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteAlbumReq.Unmarshal(m, b)
}
func (m *DeleteAlbumReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteAlbumReq.Marshal(b, m, deterministic)
}
func (m *DeleteAlbumReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteAlbumReq.Merge(m, src)
}
func (m *DeleteAlbumReq) XXX_Size() int {
	return xxx_messageInfo_DeleteAlbumReq.Size(m)
}
func (m *DeleteAlbumReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteAlbumReq.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteAlbumReq proto.InternalMessageInfo

func (m *DeleteAlbumReq) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type DeleteAlbumResp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteAlbumResp) Reset()         { *m = DeleteAlbumResp{} }
func (m *DeleteAlbumResp) String() string { return proto.CompactTextString(m) }
func (*DeleteAlbumResp) ProtoMessage()    {}
func (*DeleteAlbumResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_a8e6376c21f4d969, []int{3}
}

func (m *DeleteAlbumResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteAlbumResp.Unmarshal(m, b)
}
func (m *DeleteAlbumResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteAlbumResp.Marshal(b, m, deterministic)
}
func (m *DeleteAlbumResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteAlbumResp.Merge(m, src)
}
func (m *DeleteAlbumResp) XXX_Size() int {
	return xxx_messageInfo_DeleteAlbumResp.Size(m)
}
func (m *DeleteAlbumResp) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteAlbumResp.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteAlbumResp proto.InternalMessageInfo

type UploadImageReq struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AlbumId              string   `protobuf:"bytes,2,opt,name=album_id,json=albumId,proto3" json:"album_id,omitempty"`
	Data                 []byte   `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UploadImageReq) Reset()         { *m = UploadImageReq{} }
func (m *UploadImageReq) String() string { return proto.CompactTextString(m) }
func (*UploadImageReq) ProtoMessage()    {}
func (*UploadImageReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_a8e6376c21f4d969, []int{4}
}

func (m *UploadImageReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UploadImageReq.Unmarshal(m, b)
}
func (m *UploadImageReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UploadImageReq.Marshal(b, m, deterministic)
}
func (m *UploadImageReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UploadImageReq.Merge(m, src)
}
func (m *UploadImageReq) XXX_Size() int {
	return xxx_messageInfo_UploadImageReq.Size(m)
}
func (m *UploadImageReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UploadImageReq.DiscardUnknown(m)
}

var xxx_messageInfo_UploadImageReq proto.InternalMessageInfo

func (m *UploadImageReq) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UploadImageReq) GetAlbumId() string {
	if m != nil {
		return m.AlbumId
	}
	return ""
}

func (m *UploadImageReq) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type UploadImageResp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UploadImageResp) Reset()         { *m = UploadImageResp{} }
func (m *UploadImageResp) String() string { return proto.CompactTextString(m) }
func (*UploadImageResp) ProtoMessage()    {}
func (*UploadImageResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_a8e6376c21f4d969, []int{5}
}

func (m *UploadImageResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UploadImageResp.Unmarshal(m, b)
}
func (m *UploadImageResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UploadImageResp.Marshal(b, m, deterministic)
}
func (m *UploadImageResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UploadImageResp.Merge(m, src)
}
func (m *UploadImageResp) XXX_Size() int {
	return xxx_messageInfo_UploadImageResp.Size(m)
}
func (m *UploadImageResp) XXX_DiscardUnknown() {
	xxx_messageInfo_UploadImageResp.DiscardUnknown(m)
}

var xxx_messageInfo_UploadImageResp proto.InternalMessageInfo

type DownloadImageReq struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AlbumId              string   `protobuf:"bytes,2,opt,name=album_id,json=albumId,proto3" json:"album_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DownloadImageReq) Reset()         { *m = DownloadImageReq{} }
func (m *DownloadImageReq) String() string { return proto.CompactTextString(m) }
func (*DownloadImageReq) ProtoMessage()    {}
func (*DownloadImageReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_a8e6376c21f4d969, []int{6}
}

func (m *DownloadImageReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DownloadImageReq.Unmarshal(m, b)
}
func (m *DownloadImageReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DownloadImageReq.Marshal(b, m, deterministic)
}
func (m *DownloadImageReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DownloadImageReq.Merge(m, src)
}
func (m *DownloadImageReq) XXX_Size() int {
	return xxx_messageInfo_DownloadImageReq.Size(m)
}
func (m *DownloadImageReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DownloadImageReq.DiscardUnknown(m)
}

var xxx_messageInfo_DownloadImageReq proto.InternalMessageInfo

func (m *DownloadImageReq) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *DownloadImageReq) GetAlbumId() string {
	if m != nil {
		return m.AlbumId
	}
	return ""
}

type DownloadImageResp struct {
	Data                 []byte   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DownloadImageResp) Reset()         { *m = DownloadImageResp{} }
func (m *DownloadImageResp) String() string { return proto.CompactTextString(m) }
func (*DownloadImageResp) ProtoMessage()    {}
func (*DownloadImageResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_a8e6376c21f4d969, []int{7}
}

func (m *DownloadImageResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DownloadImageResp.Unmarshal(m, b)
}
func (m *DownloadImageResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DownloadImageResp.Marshal(b, m, deterministic)
}
func (m *DownloadImageResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DownloadImageResp.Merge(m, src)
}
func (m *DownloadImageResp) XXX_Size() int {
	return xxx_messageInfo_DownloadImageResp.Size(m)
}
func (m *DownloadImageResp) XXX_DiscardUnknown() {
	xxx_messageInfo_DownloadImageResp.DiscardUnknown(m)
}

var xxx_messageInfo_DownloadImageResp proto.InternalMessageInfo

func (m *DownloadImageResp) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type DeleteImageReq struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AlbumId              string   `protobuf:"bytes,2,opt,name=album_id,json=albumId,proto3" json:"album_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteImageReq) Reset()         { *m = DeleteImageReq{} }
func (m *DeleteImageReq) String() string { return proto.CompactTextString(m) }
func (*DeleteImageReq) ProtoMessage()    {}
func (*DeleteImageReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_a8e6376c21f4d969, []int{8}
}

func (m *DeleteImageReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteImageReq.Unmarshal(m, b)
}
func (m *DeleteImageReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteImageReq.Marshal(b, m, deterministic)
}
func (m *DeleteImageReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteImageReq.Merge(m, src)
}
func (m *DeleteImageReq) XXX_Size() int {
	return xxx_messageInfo_DeleteImageReq.Size(m)
}
func (m *DeleteImageReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteImageReq.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteImageReq proto.InternalMessageInfo

func (m *DeleteImageReq) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *DeleteImageReq) GetAlbumId() string {
	if m != nil {
		return m.AlbumId
	}
	return ""
}

type DeleteImageResp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteImageResp) Reset()         { *m = DeleteImageResp{} }
func (m *DeleteImageResp) String() string { return proto.CompactTextString(m) }
func (*DeleteImageResp) ProtoMessage()    {}
func (*DeleteImageResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_a8e6376c21f4d969, []int{9}
}

func (m *DeleteImageResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteImageResp.Unmarshal(m, b)
}
func (m *DeleteImageResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteImageResp.Marshal(b, m, deterministic)
}
func (m *DeleteImageResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteImageResp.Merge(m, src)
}
func (m *DeleteImageResp) XXX_Size() int {
	return xxx_messageInfo_DeleteImageResp.Size(m)
}
func (m *DeleteImageResp) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteImageResp.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteImageResp proto.InternalMessageInfo

type ListImageReq struct {
	AlbumId              string   `protobuf:"bytes,1,opt,name=album_id,json=albumId,proto3" json:"album_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListImageReq) Reset()         { *m = ListImageReq{} }
func (m *ListImageReq) String() string { return proto.CompactTextString(m) }
func (*ListImageReq) ProtoMessage()    {}
func (*ListImageReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_a8e6376c21f4d969, []int{10}
}

func (m *ListImageReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListImageReq.Unmarshal(m, b)
}
func (m *ListImageReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListImageReq.Marshal(b, m, deterministic)
}
func (m *ListImageReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListImageReq.Merge(m, src)
}
func (m *ListImageReq) XXX_Size() int {
	return xxx_messageInfo_ListImageReq.Size(m)
}
func (m *ListImageReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ListImageReq.DiscardUnknown(m)
}

var xxx_messageInfo_ListImageReq proto.InternalMessageInfo

func (m *ListImageReq) GetAlbumId() string {
	if m != nil {
		return m.AlbumId
	}
	return ""
}

type ListImageResp struct {
	Id                   []string `protobuf:"bytes,1,rep,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListImageResp) Reset()         { *m = ListImageResp{} }
func (m *ListImageResp) String() string { return proto.CompactTextString(m) }
func (*ListImageResp) ProtoMessage()    {}
func (*ListImageResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_a8e6376c21f4d969, []int{11}
}

func (m *ListImageResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListImageResp.Unmarshal(m, b)
}
func (m *ListImageResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListImageResp.Marshal(b, m, deterministic)
}
func (m *ListImageResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListImageResp.Merge(m, src)
}
func (m *ListImageResp) XXX_Size() int {
	return xxx_messageInfo_ListImageResp.Size(m)
}
func (m *ListImageResp) XXX_DiscardUnknown() {
	xxx_messageInfo_ListImageResp.DiscardUnknown(m)
}

var xxx_messageInfo_ListImageResp proto.InternalMessageInfo

func (m *ListImageResp) GetId() []string {
	if m != nil {
		return m.Id
	}
	return nil
}

func init() {
	proto.RegisterType((*CreateAlbumReq)(nil), "go.micro.srv.image.CreateAlbumReq")
	proto.RegisterType((*CreateAlbumResp)(nil), "go.micro.srv.image.CreateAlbumResp")
	proto.RegisterType((*DeleteAlbumReq)(nil), "go.micro.srv.image.DeleteAlbumReq")
	proto.RegisterType((*DeleteAlbumResp)(nil), "go.micro.srv.image.DeleteAlbumResp")
	proto.RegisterType((*UploadImageReq)(nil), "go.micro.srv.image.UploadImageReq")
	proto.RegisterType((*UploadImageResp)(nil), "go.micro.srv.image.UploadImageResp")
	proto.RegisterType((*DownloadImageReq)(nil), "go.micro.srv.image.DownloadImageReq")
	proto.RegisterType((*DownloadImageResp)(nil), "go.micro.srv.image.DownloadImageResp")
	proto.RegisterType((*DeleteImageReq)(nil), "go.micro.srv.image.DeleteImageReq")
	proto.RegisterType((*DeleteImageResp)(nil), "go.micro.srv.image.DeleteImageResp")
	proto.RegisterType((*ListImageReq)(nil), "go.micro.srv.image.ListImageReq")
	proto.RegisterType((*ListImageResp)(nil), "go.micro.srv.image.ListImageResp")
}

func init() { proto.RegisterFile("proto/image/image.proto", fileDescriptor_a8e6376c21f4d969) }

var fileDescriptor_a8e6376c21f4d969 = []byte{
	// 350 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x54, 0xcf, 0x4f, 0xc2, 0x30,
	0x14, 0x5e, 0x01, 0x11, 0x9f, 0x88, 0xf2, 0x2e, 0x22, 0x17, 0x67, 0xd5, 0x88, 0x97, 0x69, 0xf4,
	0x68, 0x3c, 0x18, 0xb9, 0x90, 0x68, 0x4c, 0x30, 0x24, 0x26, 0x1e, 0xcc, 0x70, 0x0d, 0x69, 0x02,
	0xb6, 0xae, 0x53, 0xff, 0x10, 0xff, 0x61, 0xd3, 0x2e, 0xcc, 0x76, 0x36, 0x60, 0xb8, 0x10, 0xd6,
	0x7e, 0x3f, 0xde, 0xde, 0xf7, 0x65, 0xb0, 0x2b, 0x53, 0x91, 0x89, 0x33, 0x3e, 0x8b, 0x27, 0x2c,
	0xff, 0x8d, 0xcc, 0x09, 0xe2, 0x44, 0x44, 0x33, 0xfe, 0x9a, 0x8a, 0x48, 0xa5, 0x9f, 0x91, 0xb9,
	0xa1, 0x21, 0xb4, 0x6e, 0x53, 0x16, 0x67, 0xec, 0x66, 0x3a, 0xfe, 0x98, 0x0d, 0xd9, 0x3b, 0xb6,
	0xa0, 0xc2, 0x93, 0x0e, 0x09, 0x49, 0x6f, 0x63, 0x58, 0xe1, 0x09, 0x6d, 0xc3, 0xb6, 0x83, 0x50,
	0x52, 0x93, 0xfa, 0x6c, 0xca, 0x16, 0x93, 0x1c, 0x84, 0x92, 0xf4, 0x01, 0x5a, 0x23, 0x39, 0x15,
	0x71, 0x32, 0xd0, 0xc6, 0x1e, 0x12, 0xee, 0x41, 0x23, 0xd6, 0xf0, 0x17, 0x9e, 0x74, 0x2a, 0xe6,
	0x74, 0xdd, 0x3c, 0x0f, 0x12, 0x44, 0xa8, 0x25, 0x71, 0x16, 0x77, 0xaa, 0x21, 0xe9, 0x35, 0x87,
	0xe6, 0xbf, 0xf6, 0x70, 0x04, 0x95, 0xa4, 0xd7, 0xb0, 0xd3, 0x17, 0x5f, 0x6f, 0x2b, 0xba, 0xd0,
	0x13, 0x68, 0x97, 0xe8, 0x4a, 0x16, 0xd6, 0xc4, 0xb2, 0xbe, 0x9a, 0x2f, 0x60, 0x15, 0x97, 0x62,
	0x37, 0xbf, 0x73, 0x9f, 0x42, 0xf3, 0x8e, 0xab, 0xac, 0x50, 0xb3, 0xd9, 0xc4, 0x65, 0xef, 0xc3,
	0x96, 0x05, 0x55, 0xb2, 0x70, 0xae, 0xe6, 0xce, 0x17, 0xdf, 0x35, 0x58, 0x33, 0xb7, 0xf8, 0x04,
	0x9b, 0x56, 0x72, 0x48, 0xa3, 0xbf, 0xf9, 0x47, 0x6e, 0xf8, 0xdd, 0xc3, 0xa5, 0x18, 0x25, 0x69,
	0xa0, 0x95, 0xad, 0x78, 0xfd, 0xca, 0x6e, 0x43, 0xfc, 0xca, 0xe5, 0x8e, 0x04, 0x38, 0x82, 0x7a,
	0x1e, 0xaa, 0x5f, 0xd4, 0x6d, 0x90, 0x5f, 0xb4, 0x5c, 0x8a, 0xa0, 0x47, 0xf0, 0x19, 0x1a, 0xf3,
	0x64, 0xf1, 0xc8, 0x3b, 0x49, 0xa9, 0x36, 0xdd, 0xe3, 0x7f, 0xa0, 0xb4, 0xf8, 0x39, 0xc1, 0x47,
	0xa8, 0xe7, 0x2f, 0xb2, 0x68, 0x11, 0x8b, 0x67, 0x2e, 0x17, 0x22, 0xc0, 0x7b, 0xa8, 0xe9, 0x9c,
	0x31, 0xf4, 0xc1, 0xed, 0xb2, 0x74, 0x0f, 0x96, 0x20, 0xb4, 0xdc, 0xb8, 0x6e, 0x3e, 0x01, 0x97,
	0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x12, 0x9b, 0x2d, 0xa2, 0x1d, 0x04, 0x00, 0x00,
}
